2018-02-07 12:33:38,761 ERROR: Exception on /user/ludo [GET] [in /home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kahll/Flask-Administration/app/routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kahll/Flask-Administration/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kahll/Flask-Administration/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/kahll/Flask-Administration/app/templates/base.html", line 46, in block "content"
    {% block app_content %}
  File "/home/kahll/Flask-Administration/app/templates/user.html", line 17, in block "app_content"
    {% include '_post.html' %}
  File "/home/kahll/Flask-Administration/app/templates/_post.html", line 12, in top-level template code
    sayd {{ moment(post.timestamp).fromNow() }}:<br>
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_moment.py", line 86, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_moment.py", line 76, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_moment.py", line 73, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
2018-02-07 12:33:52,448 ERROR: Exception on /user/ludo [GET] [in /home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kahll/Flask-Administration/app/routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kahll/Flask-Administration/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kahll/Flask-Administration/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/kahll/Flask-Administration/app/templates/base.html", line 46, in block "content"
    {% block app_content %}
  File "/home/kahll/Flask-Administration/app/templates/user.html", line 17, in block "app_content"
    {% include '_post.html' %}
  File "/home/kahll/Flask-Administration/app/templates/_post.html", line 12, in top-level template code
    sayd {{ moment(post.timestamp).fromNow() }}:<br>
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_moment.py", line 86, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_moment.py", line 76, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/home/kahll/Flask-Administration/env/lib/python3.4/site-packages/flask_moment.py", line 73, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
2018-02-07 12:36:43,318 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:49]
2018-02-07 12:38:35,860 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:49]
2018-02-07 12:39:09,755 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:49]
2018-02-07 12:39:58,306 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:49]
2018-02-07 12:40:49,186 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:49]
2018-02-07 12:41:53,393 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:49]
2018-02-07 12:42:24,703 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:49]
2018-02-07 20:09:34,911 INFO: Microblog startup [in /home/kahll/Flask-Administration/app/__init__.py:53]
